### ISSUE TITLE
issue 的練習

### ISSUE THREAD

**Issue by yangfengpu** [yangfengpu/hacker_play_ground#2]
- 練習在 issue 上加 label, 發新 issue 並指定給隊友
- close issue
- 練習如何使用 milestone

**Comment by ghost** [comment]
issue:http://blog.miniasp.com/post/2014/04/08/GitHub-Issue-Search-Tips.aspx
milestone:https://github.com/gejiawen/workflows/blob/master/requirements-base-on-milestone.md

**Comment by ghost** [comment]
完成！！
